[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/b"
  status = 302

[[redirects]]
  from = "/b/*"
  to = "/b/index.html"
  status = 200

[[redirects]]
  from = "/a"
  to = "/a/index.html"
  status = 404 